### ISSUE TITLE
UWP compatibility

### ISSUE THREAD

**Issue by rushfrisby** [madwizard-thomas/winusbnet#15]
Is there any way to convert the API so that it can be used with UWP apps? I would like to use this on Windows 10 IoT Core with a UWP app and it looks like most of it can be used, but there are references to the Unwrapped and ThreadPool that aren't available. I'm not sure what the UWP equivalent of Unwrapped would be.

**Comment by madwizard-thomas** [comment]
Sorry, I have no experience with UWP apps and am not sure of the requirements. The ThreadPool class is only used for asynchronous calls so you could remove those methods if you don't mind using a customized version. I'm not sure what you mean by Unwrapped.

**Comment by rushfrisby** [comment]
Sorry the type I meant to type is called Overlapped. It is [used in the WinUSBDevice](https://github.com/madwizard-thomas/winusbnet/blob/master/WinUSBNet/API/WinUSBDevice.cs#L307) class a bunch of times. The ThreadPool stuff I think would be easy enough to convert but I have no experience with using Overlapped. It looks like it does some memory mapping? I can't even find much documentation on it.

**Comment by madwizard-thomas** [comment]
I don't know if WinUSB is available at all in UWP apps, I think you are supposed to use the classes in the [Windows.Devices.Usb](https://msdn.microsoft.com/en-us/library/windows/apps/windows.devices.usb) namespace.
