### ISSUE TITLE
Got an exception when invoke WinUsb_Initialize

### ISSUE THREAD

**Issue by Rhuaer** [madwizard-thomas/winusbnet#16]
I get usbDeviceInfo with guid {4D1E55B2-F16F-11CF-88CB-001111000030}.
But if I use the usbDeviceInfo to initialize an UsbDevice, I get the exception message in WinUsbDevice.InitializeDevice(). 
The message is "Failed to initialize WinUSB handle. Device might not be connected.", but the usb device is always connecting.

**Comment by madwizard-thomas** [comment]
Can you share the exact code you use?

**Comment by madwizard-thomas** [comment]
Actually, I looked up the guid in google and it appears to be related to HID devices. Are you trying to open a HID device with WinUSB? Only devices that use a WinUSB driver can be connected to with WinUSB. HID devices require a different library.

**Comment by Rhuaer** [comment]
[GUID_DEVINTERFACE_USB_DEVICE](https://msdn.microsoft.com/en-us/library/windows/hardware/ff545972(v=vs.85).aspx) equals to {4D1E55B2-F16F-11CF-88CB-001111000030}.
The code is very simple.
```csharp
            Guid usbGuid = Guid.Parse("{A5DCBF10-6530-11D2-901F-00C04FB951ED}");
            USBDeviceInfo[] details = USBDevice.GetDevices(usbGuid);
            USBDeviceInfo deviceInfo = details[0];
            USBDevice imageDevice = new USBDevice(deviceInfo);

**Comment by Rhuaer** [comment]
Now I got an error code, ERROR_NOT_ENOUGH_MEMORY,  after calling WinUsbDevice.InitializeDevice().

**Comment by madwizard-thomas** [comment]
That is a different guid than you are using in the code. What kind of device are you trying to connect to? Does its driver .inf file specify WinUSB as its driver?

**Comment by Rhuaer** [comment]
> Does its driver .inf file specify WinUSB as its driver?

yeah, I forgot to do that.
