### ISSUE TITLE
DeviceNotifyHook should not need Windows Forms control

### ISSUE THREAD

**Issue by andrasfuchs** [madwizard-thomas/winusbnet#17]
I tried to use the attachment and detachment events in a console application, but I was unable to do so. I'm not sure if I missed something, but I found only the USBNotifier class, which needs a Windows Forms control as a parameter in its constructor. Is there any other way to accomplish device attachment/removal detection?

**Comment by madwizard-thomas** [comment]
Duplicate of #11
