### ISSUE TITLE
Asynchronous communication sample

### ISSUE THREAD

**Issue by andrasfuchs** [madwizard-thomas/winusbnet#18]
I could use the library to implement synchronous data transfers using the pipes. I also would like to use the asynch data transfer feature, but I could find that in the wiki.

Could you help me to find the right documentation and/or code samples?

**Comment by madwizard-thomas** [comment]
There aren't much documentation or samples but the API reference is pretty complete. For asynchronous I/O it follows the asynchronous programming model (APM) using the IAsyncResult interface. Use the BeginRead and BeginWrite functions on the pipes. For more details: https://msdn.microsoft.com/en-us/library/ms228963(v=vs.110).aspx

**Comment by andrasfuchs** [comment]
Thank you!
