### ISSUE TITLE
Problems with USB3.0 Ports

### ISSUE THREAD

**Issue by fiosimmank** [madwizard-thomas/winusbnet#21]
Communication is working fine under windows 10 with older PC with USB 2.0 Ports only with 2 different pcs.
With newer PCs (USB 3.0 Ports) communication gets stuck after about 10 readpipe commands, readpipe times out although mikrocontroller still has data in TX FIFOs. Next readpipe goes fine if done by hand after a few seconds, but endlessly fails if done in a while loop. Same for RAW mode. Do you have any idea what i could do to get communication working?

**Comment by madwizard-thomas** [comment]
Can you show some code or error messages?

**Comment by fiosimmank** [comment]
Init:
`m_oUSBDevice = USBDevice.GetSingleDevice(GUID); 
m_oUSBDevice.Interfaces[0].InPipe.Policy.PipeTransferTimeout = 200; `
(same for Timeout 5000 or infinite, same for raw policy)

Readout (at the moment called by button after device has 200 bytes to send in transmit fifo buffer):
`byte[] data = new byte[25500];
            int len2 = 0;
            while (len2 == 0)
            {
                try
                {
                    len2 = m_oUSBDevice.Interfaces[0].InPipe.Read(data);
                }
                catch (Exception e)
                {
                }

                Console.WriteLine("Received " + len2.ToString() + " Bytes");
            }`
only exception is semaphore timeout as expected. next readout in while loop also fails, but if i insert a 100ms wait time before the next InPipe.Read it successfully gets the data that the device has to offer

**Comment by fiosimmank** [comment]
I solved the issue. I had MaximumPacketSize set to 255 bytes in the device, but USB 2.0 allows only exact 512 Bytes.
