### ISSUE TITLE
USBPipe.BeginRead Asynchronous Callback not called if data packet size = 64Bytes

### ISSUE THREAD

**Issue by mfranke5** [madwizard-thomas/winusbnet#24]
I have a Full-Speed WinUSB Device with MaxPacketSize set to 64Bytes. I have set up an interrupt pipe via Endpoint 1. I noted when the device returns 64 bytes on Endpoint 1 the callback is never called, if it is any other size it will return. For now I'm working around it by having the device send an extra "dummy" byte if the length is 64. I've confirmed this issue with a USB trace to verify data was sent.

static USBPipe Pipe;
Pipe = SelectedUnit.Interfaces.FirstOrDefault().InPipe;
Pipe.BeginRead(dataInBuffer, 0, 64, new AsyncCallback(_usb_ipt_data_rc), null);

**Comment by madwizard-thomas** [comment]
The library is a pretty thin wrapper over the windows API, I don't see any obvious errors in the code that can cause this. What kind of device are you using? IIRC bulk transfers that have the exact max packet size need an additional zero length packet to indicate to the host that the transfer is finished. Not having this packet could cause this problem I think.

**Comment by mfranke5** [comment]
You are correct, I should have checked the spec first... The device's endpoint is an interrupt endpoint and as you point out: USB 2.0 Spec 5.7.3: "An interrupt transfer is complete when the endpoint...Transfers a packet with a payload size less than wMaxPacketSize or transfers a zero-length packet". Sorry for the trouble!
