### ISSUE TITLE
Trezor Hardwarewallet Error Code 8 on WinUsb_Initialize

### ISSUE THREAD

**Issue by MelbourneDeveloper** [madwizard-thomas/winusbnet#25]
I am attempting to integrate with a cryptocurrency hardwarewallet called Trezor (https://trezor.io/). I have integrated via Hid, and USB across multiple platforms. It works on Android, UWP, and Windows (via LibUsbDotNet). The repo is here: https://github.com/MelbourneDeveloper/Trezor.Net. But, for some reason, when I try to use WinUsb, I get an error code of 8 (ERROR_NOT_ENOUGH_MEMORY). This is nothing wrong with your library, but I was wondering if you've got any ideas why this might occur...

At first I thought my code was just wrong, but the exact same problem is happening with your library here: https://github.com/madwizard-thomas/winusbnet/blob/8f62d751a99be1e31d34b91115715d60aeff2dfc/WinUSBNet/API/WinUSBDevice.cs#L225 

Here is a long discussion on it:
https://stackoverflow.com/questions/53689682/windows-api-usb-io-winusb-dll

I would be so grateful if you could point me in the right direction.

I'm on windows 10. Could this be an issue? Several devices have the same issue.

**Comment by madwizard-thomas** [comment]
Hi! Sorry I have no ideas as to why the error occurs. Maybe you can use wireshark with the usb plugin to capture the USB traffic and see if anything is wrong there. The library is a thin wrapper around the WinUSB library so if the api itself fails there is probably something wrong with the parameters. Do you have the right GUIDs? Is the driver .inf correct? 
Closing this issue as it is unlikely to be a bug in the library itself.
