### ISSUE TITLE
No USb Devices populated when using GetDevice #

### ISSUE THREAD

**Issue by Josef-Ouano** [madwizard-thomas/winusbnet#29]
Hello, May I know if I still need WInUSB drivers so that my USB devices can be visible when using GetDevice()? How do I install them? How do I get this Library to work? I'm drawing a blank.

**Comment by madwizard-thomas** [comment]
Yes, only devices using WinUSB can be used with the library. You need a custom ini file, an example is in the wiki. Or use something like [zadig](https://zadig.akeo.ie/) to force a driver. WinUSB is for custom devices or devices not implementing any of the standard classes (hid, mass storage etc.), you'll need some basic knowledge of USB to use the library.
