### ISSUE TITLE
Documentaton Link Broken

### ISSUE THREAD

**Issue by HydeNaut** [madwizard-thomas/winusbnet#31]
I'm very new to this area of programming so my ignorance abounds, but your link to documentation is [broken](url)

**Comment by madwizard-thomas** [comment]
Can you point to the page that links to the broken page? Your own link is broken :)

**Comment by HydeNaut** [comment]
Silly me and thanks for getting back.
The issue is on [this page](https://github.com/madwizard-thomas/winusbnet/wiki/Documentation)
![image](https://user-images.githubusercontent.com/67781825/89040060-6c367800-d343-11ea-930c-2944eb8463aa.png)

**Comment by madwizard-thomas** [comment]
Thanks, this was indeed a very old link from when google code was still a thing. Fixed now, the correct link is:
https://madwizard-thomas.github.io/winusbnet/docs
Thanks!
